### Deployment ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
  annotations:
    kubernetes.io/change-cause: "httpd v2 image"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: pranavdhopey/myweb:httpdv2  # Version 2
        ports:
        - containerPort: 80
